version: 2
jobs:
  build:
    docker:
      - image: particleflux/circleci-bats-kcov:latest

    steps:
    - checkout

    # install codeclimate test reporter
    - restore_cache:
        keys:
        - v3-dependencies

    - run:
        command: |
          if [[ ! -f "/tmp/cc-test-reporter" ]]; then
            curl -sSL -o /tmp/cc-test-reporter \
              https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          fi
          chmod +x /tmp/cc-test-reporter

    - save_cache:
        paths:
        - /tmp/cc-test-reporter
        key: v3-dependencies

    - run:
        name: Activate shellmock
        command: |
          mkdir ~/bin/
          cp .circleci/shellmock ~/bin/

    - run:
        command: |
          export PATH="$HOME/bin:$PATH"
          /tmp/cc-test-reporter before-build
          kcov --include-path=. --exclude-path=test coverage bats test/
          xml="$(ls -1 coverage/bats*/cobertura.xml | head -1)"

          # removing trailing slash in cobertura <source>
          # this works around an issue with the codeclimate formatter
          sed -ri "s#<source>(.+)/</source>#<source>\1</source>#" "$xml"

          /tmp/cc-test-reporter format-coverage $xml --input-type cobertura
          /tmp/cc-test-reporter upload-coverage

    - store_artifacts:
        path: coverage
